# Generated by Django 3.2 on 2021-06-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carPost_moteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField(max_length=50)),
                ('price', models.IntegerField(max_length=20)),
                ('vendor', models.TextField(max_length=100)),
                ('year', models.IntegerField(max_length=4)),
                ('km', models.IntegerField(max_length=20)),
                ('carb', models.TextField(max_length=30)),
                ('trans', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='carPost_wandaloo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField(max_length=50)),
                ('option', models.TextField(max_length=100)),
                ('price', models.IntegerField(max_length=20)),
                ('vendor', models.TextField(max_length=100)),
                ('tel', models.TextField(max_length=13)),
                ('year', models.IntegerField(max_length=4)),
                ('city', models.TextField(max_length=50)),
                ('main', models.TextField(max_length=30)),
                ('km', models.IntegerField(max_length=20)),
                ('carb', models.TextField(max_length=30)),
                ('trans', models.TextField(max_length=30)),
            ],
        ),
    ]
