# Generated by Django 3.2 on 2021-06-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0002_auto_20210613_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='carPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField(max_length=50)),
                ('option', models.TextField(max_length=100)),
                ('price', models.IntegerField()),
                ('vendor', models.TextField(max_length=100)),
                ('year', models.IntegerField()),
                ('city', models.TextField(max_length=50)),
                ('main', models.TextField(max_length=30)),
                ('km', models.IntegerField()),
                ('carb', models.TextField(max_length=30)),
                ('trans', models.TextField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='carPost_moteur',
        ),
        migrations.DeleteModel(
            name='carPost_wandaloo',
        ),
    ]
