# Generated by Django 3.2 on 2021-06-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0005_carpost_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpost',
            name='img',
            field=models.URLField(null=True),
        ),
    ]
