# Generated by Django 3.2 on 2021-05-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20210515_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_data',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null='true'),
            preserve_default='true',
        ),
    ]
