# Generated by Django 3.2 on 2021-05-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20210515_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_data',
            name='source',
            field=models.CharField(blank='false', max_length=100, null='false'),
            preserve_default='false',
        ),
    ]
