# Generated by Django 3.2 on 2021-05-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_car_data_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car_data',
            old_name='source',
            new_name='url',
        ),
    ]
